### PR TITLE
Fix typos and improve readability

### PR DESCRIPTION
**Pull request by rakleed**
When I send a request to Malwarebytes support, I receive a reply that no licenses are registered to my email, so they are closing the request. I'm not sure if this link is even necessary.

### CODE REVIEW

**Comment by yaronelh** [comment]
Thanks for the contribution, I appreciate it. Unfortunately a lot of the changes are changes I don't want to make, and don't have an easy way to separate them from the others.

Do you know of any way of committing part of the changes?

**Comment by rakleed** [comment]
I may do a separate PR, but for the most part I've corrected typos in addition to updating information on the two vendors.

**Comment by yaronelh** [comment]
Yeah it's great, If you can do separate poll requests for the changes that would be great.
That way I can do the merge separately

**Comment by yaronelh** [comment]
Would you mind if I do the changes manually without a pull request?

**Comment by rakleed** [comment]
@yaronelh done. Please first take a look at #68 and #69.

**Comment by rakleed** [comment]
@yaronelh why did you just close PR?

**Pull request closed without merging**
