### PR TITLE
Update Symantec contact info

### PR DESCRIPTION
**Pull request by rakleed**
- Update link and email to send false positives.
- Add case number information.

### CODE REVIEW

**Comment by yaronelh** [comment]
Hi @rakleed 
what is broadcom.com ?

**Comment by rakleed** [comment]
Broadcom acquired corporate security solutions from Symantec: https://en.wikipedia.org/wiki/Broadcom_Inc.#Symantec_enterprise_security

And I sent information about false positives both through the form and by email - both options work.

**Review by yaronelh — APPROVED** [review]
I left both options

**Comment by rakleed** [comment]
@yaronelh email avsubmit@symantec.com no longer works.

image

**Comment by yaronelh** [comment]
👍

**Pull request merged**
