### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drveresh**
Added the VirtyTotal's main contact form for reporting false positives.

### CODE REVIEW

**Comment by yaronelh** [comment]
Have you ever gotten an answer from them regarding the report of a false positive? 
Usually they write something like them being just a publisher of results, they don't do any validation of what they publish, and as far as I know, they don't have any mechanism to report to them inaccuracies when they appear in their public results.

In the past, they used to contact the security vendors or help you contact the security vendors if you haven't succeeded doing so over 30 days or something like that, not sure that it's still happening today. Last I've contacted them a while ago I haven't gotten any response 

Let me know if that has changed

**Comment by drveresh** [comment]
@yaronelh It is not necessarily the report of a false positive, but the team (contact@virustotal.com) **did respond** to several queries and helped address a few issues.  Now, they have an option "**Reanalyze**" on UI that will refresh the status of links from various vendors and update accordingly. I just did for an endpoint for a false positive, and after Reanalyze it did mark some vendors` status as Green or Clean.

There is a clear **false positive** category in their [contact form](https://www.virustotal.com/gui/contact-us/technical-support), so they should response accordingly, if not some of us should drive this initiative further.  This PR will help users get their contact form when really needed, at least in my case, as my products needs to validate at least 10,000 new links per day.

**Comment by yaronelh** [comment]
I'll add it outside the table in an area that is already talking about VirusTotal

**Comment by yaronelh** [comment]
(added)

**Pull request closed without merging**
