### PR TITLE
Add Google to the contact information table

### PR DESCRIPTION
**Pull request by ahmedosama007**
Add instructions on how to report false positives to Google.

### CODE REVIEW

**Comment by yaronelh** [comment]
Cool, interesting approach, Is that something you've tried?
Also the list is alphabetical, I can do it manually on my end but if you want it as part of the commit you'll need to do it on your side (Placeing it in the correct alphabetical location)

**Comment by ahmedosama007** [comment]
> Cool, interesting approach, Is that something you've tried?

Yes, but Google's response is not guaranteed.

https://github.com/yaronelh/False-Positive-Center/assets/15314541/a8d331a3-2b49-4f0d-a7d6-80ea642b5bdd

> Also the list is alphabetical, I can do it manually on my end but if you want it as part of the commit you'll need to do it on your side (Placeing it in the correct alphabetical location)

Fixed the Google contact information position in the last commit.

**Comment by yaronelh** [comment]
thanks, I'll also add that you probably shouldn't do that on your main Google account, for even the slightest possibility that your account will be suspended for some reason, after all we're talking about Google here.

**Comment by ahmedosama007** [comment]
I can confirm that Google has responded to the file review request, and the false detection has been removed. Additionally, there seems to be a connection between Google and ClamAV.

**Comment by yaronelh** [comment]
They have some connection with ClamAV, Interesting. How did you find that out?

**Comment by ahmedosama007** [comment]
> They have some connection with ClamAV, Interesting. How did you find that out?


I had two executables that were flagged by ClamAV and Google on VirusTotal. After Google removed their detections in response to file review requests, I noticed that the ClamAV flags were also removed.

**Comment by yaronelh** [comment]
could be that they're also both following some central database.

**Comment by teijiIshida** [comment]
I'm trying to report my app for false positive by Google. When I get to the Open With > Preview step. There is no "This file looks suspicious. It is visible only to the owner." How can I send my file for Gogole to fix this?

**Comment by ddernon** [comment]
@teijiIshida 

> I'm trying to report my app for false positive by Google. When I get to the Open With > Preview step. There is no "This file looks suspicious. It is visible only to the owner." How can I send my file for Google to fix this?

As can be guessed from the video demo, from the icon next to the flag icon, the flagging seems to only get triggered if you share the file. So in my case, what I did was share it to a secondary account, and then I had the option to send it for review, from the first account (and also, after briefly appearing in my secondary account's Drive, it vanished from it)

**Pull request merged**
