### PR TITLE
Add submission form for eScan

### PR DESCRIPTION
**Pull request by rakleed**

### CODE REVIEW

**Review by yaronelh — COMMENTED** [review]
I'm on my phone right now so I can't do the change but the link seems to be wrong

**Comment by rakleed** [comment]
I double-checked it, the link opens.

**Review by yaronelh — COMMENTED** [review]
For me it shows a big X with the message invalid department ID....

But this works I just can't change it from my phone
http://support.mwti.net/support/index.php?/Tickets/Submit

**Comment by rakleed** [comment]
This did not affect the interaction with the site in any way, but I updated the link.

**Pull request merged**
